### ISSUE TITLE
Run the database set up script using 'node /server/config/database_creation_script.js' have bugs

### ISSUE THREAD

**Issue by Nicolewxyy** [aybmab/express-redux-sample#3]
I followed the Setting up  to run database set up with `node /server/config/database_creation_script.js`, but got the error: `{ [Error: Cannot enqueue Query after fatal error.] code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }` Thanks for any help

**Comment by aybmab** [comment]
Hey @Nicolewxyy !

I actually haven't updated this project in a while... I've learned the hard way (after ignoring much advice) that writing your own sql is a bad idea. I would recommend using something like [sequelize](http://docs.sequelizejs.com/en/latest/) instead.

However, if you just want to get this project up and running, are you sure that your DB is up and running?

**Comment by Nicolewxyy** [comment]
yes, my server is running. but i can't find /tmp/mysql.sock file in my computer, i don't know why.

**Comment by aybmab** [comment]
You can also connect to the DB using different params. Check out: https://github.com/felixge/node-mysql#establishing-connections

**Comment by Nicolewxyy** [comment]
Thanks for your reply, I will try it !
